export { default as NavBar } from "./header/NavBar";
export { default as SideBar } from "./header/SideBar";
export { default as Logo } from "./header/Logo";
export { default as Background } from "./background/Background.jsx";
export { default as Slider } from "./slider/Slider.jsx";
export { default as PosterCard } from "./card/PosterCard";
export { default as PosterCardList } from "./card/PosterCardList";
export { default as UpcomingCard } from "./card/UpcomingCard";
export { default as UpcomingCardList } from "./card/UpcomingCardList";
